version: '3.9'

services:
  app:
    container_name: my-pub-app
    build: .
    ports:
      - "4200:80"
    networks:
      - mypubnetworks
  api:
    container_name: beer-service
    image: olaf67/mypubbeerservice
    ports:
      - 5001:80
    networks:
      - mypubnetworks

networks:
  mypubnetworks: